DROP PROCEDURE IF EXISTS `ADD_TIMESTAMPS`;
DELIMITER //
CREATE PROCEDURE `ADD_TIMESTAMPS`()
BEGIN
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN
    END;

    ALTER TABLE `session_recipients`
        ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
END //
DELIMITER ;
CALL `ADD_TIMESTAMPS`();
DROP PROCEDURE `ADD_TIMESTAMPS`;
